# Generated by Django 2.1.4 on 2018-12-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='doc',
            field=models.FileField(blank=True, upload_to='post_docs'),
        ),
    ]
