# Generated by Django 2.1.4 on 2018-12-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_post_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='doc',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='post_image'),
        ),
    ]
